name: d9-httpbin
recipe: drupal9
config:
  webroot: web
  database: mariadb
  xdebug: true
#services:
#  api:
#    type: compose
#    overrides:
#      image: kennethreitz/httpbin
#      ports:
#        - 80
